"""edit profile

Revision ID: 808a609d38f7
Revises: 62216023ec67
Create Date: 2018-03-05 10:24:42.530678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808a609d38f7'
down_revision = '62216023ec67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
