"""add fishes

Revision ID: c7e7dddd4936
Revises: 04f485073d17
Create Date: 2018-03-11 15:11:10.899885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e7dddd4936'
down_revision = '04f485073d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishes', sa.Column('commercial', sa.Text(), nullable=True))
    op.add_column('fishes', sa.Column('danger_reason', sa.Text(), nullable=True))
    op.add_column('fishes', sa.Column('domestication', sa.Text(), nullable=True))
    op.add_column('fishes', sa.Column('foods', sa.Text(), nullable=True))
    op.add_column('fishes', sa.Column('growth', sa.Text(), nullable=True))
    op.add_column('fishes', sa.Column('protection', sa.Text(), nullable=True))
    op.add_column('fishes', sa.Column('protection_sugession', sa.Text(), nullable=True))
    op.add_column('fishes', sa.Column('quantity', sa.Text(), nullable=True))
    op.add_column('fishes', sa.Column('reproduce', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fishes', 'reproduce')
    op.drop_column('fishes', 'quantity')
    op.drop_column('fishes', 'protection_sugession')
    op.drop_column('fishes', 'protection')
    op.drop_column('fishes', 'growth')
    op.drop_column('fishes', 'foods')
    op.drop_column('fishes', 'domestication')
    op.drop_column('fishes', 'danger_reason')
    op.drop_column('fishes', 'commercial')
    # ### end Alembic commands ###
